// <auto-generated />
namespace HBS_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pateint_doctor_model_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pateint_doctor_model_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201711211727480_pateint_doctor_model_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
